import { Device } from '../models'

export const mockDevices: Device[] = [
  {
    id: 'device-door-1',
    name: 'Court 1 - 門禁',
    type: 'DOOR',
    courtId: 'court-1',
    status: 'ONLINE',
    lastSeen: new Date(),
    lastAction: 'LOCKED',
  },
  {
    id: 'device-lights-1',
    name: 'Court 1 - 照明',
    type: 'LIGHTS',
    courtId: 'court-1',
    status: 'ONLINE',
    lastSeen: new Date(),
    lastAction: 'ON',
  },
  {
    id: 'device-fans-1',
    name: 'Court 1 - 風扇',
    type: 'FANS',
    courtId: 'court-1',
    status: 'ONLINE',
    lastSeen: new Date(),
    lastAction: 'ON',
  },
  {
    id: 'device-cam-1-nw',
    name: 'Court 1 - 攝像頭 (NW)',
    type: 'CAMERA',
    courtId: 'court-1',
    status: 'ONLINE',
    lastSeen: new Date(),
  },
  {
    id: 'device-cam-1-ne',
    name: 'Court 1 - 攝像頭 (NE)',
    type: 'CAMERA',
    courtId: 'court-1',
    status: 'ONLINE',
    lastSeen: new Date(),
  },
  {
    id: 'device-cam-1-sw',
    name: 'Court 1 - 攝像頭 (SW)',
    type: 'CAMERA',
    courtId: 'court-1',
    status: 'ONLINE',
    lastSeen: new Date(),
  },
  {
    id: 'device-cam-1-se',
    name: 'Court 1 - 攝像頭 (SE)',
    type: 'CAMERA',
    courtId: 'court-1',
    status: 'ONLINE',
    lastSeen: new Date(),
  },
  {
    id: 'device-speaker-1',
    name: 'Court 1 - 喇叭',
    type: 'SPEAKER',
    courtId: 'court-1',
    status: 'ONLINE',
    lastSeen: new Date(),
  },
]
