import { Reservation } from '../models'
import { mockMembers } from './members'

export const mockReservations: Reservation[] = [
  {
    id: 'res-1',
    bookingCode: 'PH001',
    memberId: 'member-1',
    member: mockMembers[0],
    items: [
      {
        id: 'item-1',
        courtId: 'court-1',
        type: 'COURT',
        name: 'Court 1 - 2小時',
        startTime: new Date(Date.now() + 2 * 60 * 60 * 1000),
        endTime: new Date(Date.now() + 4 * 60 * 60 * 1000),
        price: 1000,
        playerCount: 4,
      },
    ],
    type: 'COURT',
    status: 'CONFIRMED',
    paymentStatus: 'PAID',
    totalAmount: 1000,
    qrCode: 'QR-PH001-12345',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'res-2',
    bookingCode: 'PH002',
    memberId: 'member-2',
    member: mockMembers[1],
    items: [
      {
        id: 'item-2',
        courtId: 'court-2',
        type: 'COURT',
        name: 'Court 2 - 2小時',
        startTime: new Date(Date.now() + 6 * 60 * 60 * 1000),
        endTime: new Date(Date.now() + 8 * 60 * 60 * 1000),
        price: 1000,
        playerCount: 4,
      },
    ],
    type: 'COURT',
    status: 'PENDING',
    paymentStatus: 'PENDING',
    totalAmount: 1000,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
  },
  {
    id: 'res-3',
    bookingCode: 'PH003',
    memberId: 'member-3',
    member: mockMembers[2],
    items: [
      {
        id: 'item-3',
        eventId: 'event-1',
        type: 'EVENT',
        name: '周六友誼賽',
        startTime: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
        endTime: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000),
        price: 300,
        playerCount: 1,
      },
    ],
    type: 'EVENT',
    status: 'CONFIRMED',
    paymentStatus: 'PAID',
    totalAmount: 300,
    qrCode: 'QR-PH003-12346',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
]
